# -*- coding: utf-8 -*-
"""HPC1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eV-j-0jFOhKKn9aC_2j8KalVTtPTL84W
"""

from numba import cuda
print(cuda.gpus)

cuda.is_available()

print(cuda.detect())

print("Device name: ",cuda.select_device(0))

from numba.cuda.cudadrv import enums
device = cuda.get_current_device()
attribs= [name.replace("CU_DEVICE_ATTRIBUTE_", "") for name in dir(enums) if name.startswith("CU_DEVICE_ATTRIBUTE_")]
attribs



print("CLOCK RATE :", getattr(device,'CLOCK_RATE'))

cc_cores_per_SM_dict = {
    (2,0) : 32,
    (2,1) : 48,
    (3,0) : 192,
    (3,5) : 192,
    (3,7) : 192,
    (5,0) : 128,
    (5,2) : 128,
    (6,0) : 64,
    (6,1) : 128,
    (7,0) : 64,
    (7,5) : 64,
    (8,0) : 64,
    (8,6) : 128,
    (8,9) : 128,
    (9,0) : 128,
    }

device = cuda.get_current_device()
my_sms = getattr(device, 'MULTIPROCESSOR_COUNT')
my_cc = device.compute_capability
cores_per_sm = cc_cores_per_SM_dict.get(my_cc)
total_cores = cores_per_sm*my_sms
print("total cores: " , total_cores)

print("MULTIPROCESSOR COUNT :",getattr(device, 'MULTIPROCESSOR_COUNT'))

getattr(device,'WARP_SIZE')

print("MEMORY :", cuda.current_context().get_memory_info())

print("GLOBAL_MEMORY_BUS_WIDTH :",getattr(device, 'GLOBAL_MEMORY_BUS_WIDTH'))

print("MULTIPROCESSOR COUNT :",getattr(device, 'GLOBAL_MEMORY_BUS_WIDTH'))