# -*- coding: utf-8 -*-
"""HPC_LW5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfV-u7ayFayD4GyjMCTh3pP7h7vUrjTr
"""

from numba import cuda
import matplotlib.pyplot as plt
import numpy as np
import time
import math
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

im = plt.imread("/content/drive/MyDrive/Colab Notebooks/image6.jpeg")

shape = np.shape(im)

filter = np.array(((0,0,1,2,1,0,0),
(0,3,13,22,13,3,0),
(1,13,59,97,59,13,1),
(2,22,97,159,97,22,2),
(1,13,59,97,59,13,1),
(0,3,13,22,13,3,0),
(0,0,1,2,1,0,0)))

total = sum(sum(filter))
total

filter2 = filter/total
filter2

im2 = im.copy()

#first version CPU
"""
for x in range(3,shape[0]-3):
  for y in range(3,shape[1]-3):
    r = 0
    g = 0
    b = 0

    for ni, i in enumerate(range(-3,3)):
        for nj, j in enumerate(range(-3,3)):
          r+=(im[x+i,y+j,0]*filter2[ni,nj])
          g+=(im[x+i,y+j,1]*filter2[ni,nj])
          b+=(im[x+i,y+j,2]*filter2[ni,nj])

    im2[x,y,0] = r
    im2[x,y,1] = g
    im2[x,y,2] = b
"""

"""
imgpu = Image.fromarray(im2)
imgpu.save("/content/drive/MyDrive/Colab Notebooks/image_blur_CPU1.jpeg")
"""

im3 = im.copy()

#Second version CPU
def blurfunc(image):
  imagecopy = image
  for x in range(3,shape[0]-3):
    for y in range(3,shape[1]-3):
      rgb=[0,0,0]
      for ni, i in enumerate(range(-3,3)):
        for nj, j in enumerate(range(-3,3)):
          rgb+=(image[x+i,y+j]*filter2[ni,nj])
          
      imagecopy[x,y] = rgb

  return imagecopy

for i in range(10):
  im3 = blurfunc(im3)

imgpu = Image.fromarray(im3)
imgpu.save("/content/drive/MyDrive/Colab Notebooks/image_blur_CPU3.jpeg")

#GPU1

@cuda.jit
def blurgpu1(kernel, src, dst):
  tidx = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
  tidy = cuda.threadIdx.y + cuda.blockIdx.y * cuda.blockDim.y
  r = 0
  g = 0
  b = 0

  for ni, i in enumerate(range(-3,3)):
    for nj, j in enumerate(range(-3,3)):
      r+= np.uint8(src[tidx+i,tidy+j,0]*kernel[ni,nj])
      g+= np.uint8(src[tidx+i,tidy+j,1]*kernel[ni,nj])
      b+= np.uint8(src[tidx+i,tidy+j,2]*kernel[ni,nj])
  dst[tidx, tidy, 0 ] = r
  dst[tidx, tidy, 1 ] = g
  dst[tidx, tidy, 2 ] = b

devdata = cuda.to_device(im)
devOuput = cuda.device_array(shape, np.uint8)
kerneldev = cuda.to_device(filter2)

blockSize = (16,16)
gridSize = (math.ceil(shape[0]/blockSize[0]),math.ceil(shape[1]/blockSize[1]))
blurgpu1[gridSize, blockSize](kerneldev ,devdata, devOuput)

imblurgpu = devOuput.copy_to_host()
imgpu = Image.fromarray(imblurgpu)
imgpu.save("/content/drive/MyDrive/Colab Notebooks/image_blur_GPU.jpeg")

imgpu